question_data = [
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Whistler was the codename of this Microsoft Operating System.", "correct_answer": "Windows XP",
     "incorrect_answers": ["Windows 2000", "Windows 7", "Windows 95", "Windows XP"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "On which computer hardware device is the BIOS chip located?", "correct_answer": "Motherboard",
     "incorrect_answers": ["Hard Disk Drive", "Central Processing Unit", "Graphics Processing Unit", "Motherboard"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following languages is used as a scripting language in the Unity 3D game engine?",
     "correct_answer": "C#", "incorrect_answers": ["Java", "C++", "Objective-C", "C#"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "All of the following programs are classified as raster graphics editors EXCEPT:",
     "correct_answer": "Inkscape", "incorrect_answers": ["Paint.NET", "Inkscape", "GIMP", "Adobe Photoshop"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "The computer OEM manufacturer Clevo, known for its Sager notebook line, is based in which country?",
     "correct_answer": "Taiwan",
     "incorrect_answers": ["United States", "Germany", "Taiwan", "China (People's Republic of)"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What did the name of the Tor Anonymity Network originally stand for?",
     "correct_answer": "The Onion Router",
     "incorrect_answers": ["The Onion Router", "The Only Router", "The Orange Router", "The Ominous Router"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What was the name given to Android 4.3?", "correct_answer": "Jelly Bean",
     "incorrect_answers": ["Lollipop", "Nutella", "Froyo", "Jelly Bean"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What does the acronym CDN stand for in terms of networking?",
     "correct_answer": "Content Delivery Network",
     "incorrect_answers": ["Content Distribution Network", "Content Delivery Network", "Computational Data Network",
                           "Compressed Data Network"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Generally, which component of a computer draws the most power?", "correct_answer": "Video Card",
     "incorrect_answers": ["Hard Drive", "Processor", "Power Supply", "Video Card"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which one of these is not an official development name for a Ubuntu release?",
     "correct_answer": "Mystic Mansion", "incorrect_answers": ["Mystic Mansion", "Trusty Tahr",
                                                               "Utopic Unicorn", "Wily Werewolf"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In the server hosting industry IaaS stands for...", "correct_answer": "Infrastructure as a Service",
     "incorrect_answers": ["Internet as a Service", "Internet and a Server", "Infrastructure as a Server",
                           "Infrastructure as a Service"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which coding language was the #1 programming language in terms of usage on GitHub in 2015?",
     "correct_answer": "JavaScript", "incorrect_answers": ["C#", "JavaScript", "Python", "PHP"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In CSS, which of these values CANNOT be used with the &quot;position&quot; property?",
     "correct_answer": "center", "incorrect_answers": ["static", "center", "absolute", "relative"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What is the correct term for the metal object in between "
                 "the CPU and the CPU fan within a computer system?",
     "correct_answer": "Heat Sink", "incorrect_answers": ["Heat Sink", "CPU Vent",
                                                          "Temperature Dissipator", "Heat Vent"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of these programming languages is a low-level language?", "correct_answer": "Assembly",
     "incorrect_answers": ["Python", "C#", "Pascal", "Assembly"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What does &quot;LCD&quot; stand for?", "correct_answer": "Liquid Crystal Display",
     "incorrect_answers": ["Language Control Design", "Liquid Crystal Display", "Last Common Difference",
                           "Long Continuous Design"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which operating system was released first?", "correct_answer": "Mac OS",
     "incorrect_answers": ["Windows", "Mac OS", "Linux", "OS/2"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": ".at is the top-level domain for what country?", "correct_answer": "Austria",
     "incorrect_answers": ["Austria", "Argentina", "Australia", "Angola"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of these people was NOT a founder of Apple Inc?", "correct_answer": "Jonathan Ive",
     "incorrect_answers": ["Steve Jobs", "Jonathan Ive", "Ronald Wayne", "Steve Wozniak"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What does RAID stand for?", "correct_answer": "Redundant Array of Independent Disks",
     "incorrect_answers": ["Rapid Access for Indexed Devices", "Range of Applications with Identical Designs",
                           "Randomized Abstract Identification Description", "Redundant Array of Independent Disks"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "How many bytes are in a single Kibibyte?", "correct_answer": "1024",
     "incorrect_answers": ["1024", "2400", "1000", "1240"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "The teapot often seen in many 3D modeling applications is called what?",
     "correct_answer": "Utah Teapot", "incorrect_answers": ["Utah Teapot", "Pixar Teapot",
                                                            "3D Teapot", "Tennessee Teapot"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What is the number of keys on a standard Windows Keyboard?", "correct_answer": "104",
     "incorrect_answers": ["64", "94", "76"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Unix Time is defined as the number of seconds that have elapsed since when?",
     "correct_answer": "Midnight, January 1, 1970",
     "incorrect_answers": ["Midnight, July 4, 1976", "Midnight on the creator of Unix's birthday",
                           "Midnight, January 1, 1970", "Midnight, July 4, 1980"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "How many bits make up the significand portion of a single precision floating point number?",
     "correct_answer": "23", "incorrect_answers": ["23", "8", "53", "15"]}
]
